name: Firebase Deploy

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Firebase target: default|staging|production'
        required: false
        default: 'default'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Auth to Google Cloud (service account)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install Functions deps
        working-directory: functions
        run: npm ci

      - name: Build Functions
        working-directory: functions
        run: npm run build

      - name: Select project
        run: echo "PROJECT_ID=$(if [ '${{ github.event.inputs.target }}' = 'production' ]; then echo resilientme-prod; else echo resilientme-staging; fi)" >> $GITHUB_ENV

      - name: Deploy rules, indexes, and functions
        run: |
          npm i -g firebase-tools
          firebase deploy --project $PROJECT_ID --only firestore:rules,firestore:indexes,functions
